### ISSUE TITLE
Running with gunicorn

### ISSUE THREAD

**Issue by hemangsk** [kraiz/django-crontab#49]
Hey @kraiz 😃  

I've been using django-crontab since three months now and its super awesome. I just wanted to ask if there is any special setting required to run cron jobs inside gunicorn.

Actually my scenario is that we want to make some HTTP requests through the cronjob. Now while running Django Development Server, cron jobs are working perfectly. But the issue is when I run them in Docker + gunicorn setup, the cronjobs get registered (```checked using crontab -l```) alright, but none of them work. 

Here's what I've been trying,
- Removing HTTP requests code and adding simple DB manipulation code inside my cron.py, it doesn't work either.
- Using gevent in gunicorn for asynchronous workers.

Do yo think its something related to worker processes in gunicorn, I'm having absolutely no idea about this even after a week of googleing. Any help or pointers would really be great! 

Thanks a lot!

**Comment by kraiz** [comment]
Hi @hemangsk, gunicorn is a wsgi container and will just serve http requests only. Cronjobs run as separate process in a separate environment. django-crontab tries to bridge this gap for typical linux systems so that it should just work and the developer doesn't need to understand the details. But as you're running inside a docker container you need to think about that.

If you run gunicorn within a docker container as "the" process (with maybe child worker processes) there's no cron daemon running and django-crontab will not be triggered. You maybe need to start another container from the same image for the `crond` service (the daemon which triggers cronjobs). But then again, you need to understand how docker and cron works.
