### ISSUE TITLE
Where is my crontab executable

### ISSUE THREAD

**Issue by mjdavies** [kraiz/django-crontab#54]
Hello there

Running ubuntu16, django1.10 through docker.

Can anyone tell me what the path to the crontab executable is, or how I find it?

I'm getting this error running crontab add

sh: 1: /usr/bin/crontab: not found
  adding cronjob: (d5fc228456872d633a9fd2f18a2ace15) -> ('*/5 * * * *', 'research.cron.update_feeds')
sh: 1: /usr/bin/crontab: not found

which crontab on the server replies with nothing

On a non docker ubuntu16 which crontab replies with /usr/bin/crontab

I think it's because I must be root on the container.

Anyone got any ideas on how to get around this?

**Comment by kraiz** [comment]
Hey, there's no crontab available inside a docker container when you don't install it and start it. Have a look here: https://github.com/kraiz/django-crontab/issues/49#issuecomment-286192547

I maybe should put a docker hint into the FAQ section...

**Comment by mjdavies** [comment]
Hi Kraiz, thanks for getting back to me.

Yeah, I install cron, which got me around the error of not having a crontab, but as you say, it's not running, so it wont work.

Gunicorn is the running command.

Any ideas on how I start it and start gunicorn?

I know, I could use something like honcho

**Comment by mjdavies** [comment]
This is a bloody laugh this is

Here's my Procfile

nginx: /usr/sbin/nginx
webapp: gunicorn research.wsgi --workers=3 -b 0.0.0.0:8000 --log-level debug
crontab: service cron start

Honcho start is now throwing this out

research_web    | 13:13:28 crontab.1 |  * Starting periodic command scheduler cron
research_web    | 13:13:28 crontab.1 |    ...done.
research_web    | 13:13:28 system    | crontab.1 stopped (rc=0)

**Comment by mjdavies** [comment]
Ok, something else is up here.  I just start the container with the gunicorn command, then get onto the container and run the other 2 commands, they both work fine
 
cron starts

I'm doing something wrong, I'll be back!!

**Comment by kraiz** [comment]
You-re right, you need to start it. I see 2 approaches:

The one you chosen is starting a process manager inside a container which starts the child processes (gunicorn + cron). But you need to start this processes and keep them running for the process manager (honcho, in ur case) to watch them. Starting cron via the service script will start it in the background (the command will end, but is assumed to be kindof detached and running in the background). But honcho just sees a command that stopped. Maybe start it via "cron -f".

Another way is to start 2 containers from the same docker image, which just run the different processes (which you put into honcho on the other way).

**Comment by mjdavies** [comment]
Hi Kraiz.

Ok, cron -f worked, I've got it up and running.

Once I create the container, I then add the job like this

    docker exec research_web python manage.py crontab add

That gives me this back

```` no crontab for root
  adding cronjob: (d5fc228456872d633a9fd2f18a2ace15) -> ('*/5 * * * *', 'research.cron.update_feeds')````

The update_feeds task isn't running though :-(

How do I go about seeing any sort of logs about this to try and debug why it's not happening?

There's nothing being spat out into the stdout, and django is on full debug log, so it looks like it's not getting as far as trying to run the update_feeds script.

Any ideas?

Thanks for your help with this kraiz.

**Comment by mjdavies** [comment]
Ok, got a bit more information.

Once I start the container, and run the crontab add, there is an entry into roots crontab

    */5 * * * * /usr/bin/python /code/manage.py crontab run d5fc228456872d633a9fd2f18a2ace15

And if I manually run the job on the container, it runs and works just fine

    /usr/bin/python /code/manage.py crontab run d5fc228456872d633a9fd2f18a2ace15

So it looks like the bit of all this that checks the crontab files and runs them is not doing that.

cron -f is running though, as root

**Comment by kraiz** [comment]
It should be all about why the cron-process is not picking up the crontab-file. Maybe "cron -f" isn't enough. It maybe need more parameters? Maybe the ubuntu service script gives you some hints...

**Comment by krallin** [comment]
@mjdavies cron will automatically purge all environment variables when it runs, so if your app depends on any of those (e.g. you're using a virtual environment, or rely on some environment variables), the jobs will fail to run (that's a common issue running `cron` in containers). 

Unfortunately, since `cron` also eats you log output, this can be a little tough to debug. One way to try and work around that is to send logs from your task somewhere else to get an idea of what's going wrong.

For example, alter the `crontab` generated by `django-crontab` like this, then run `cron -f`: 

```
*/5 * * * * /usr/bin/python /code/manage.py crontab run d5fc228456872d633a9fd2f18a2ace15 >> /tmp/debug.log 2>&1
```

Afterwards, wait for a little while (i.e. 5 minutes until the job runs) and check `/tmp/debug.log` to get an idea of what went wrong.

---

Now... I apologize for barging in like this in this thread, but I wrote an open-source crontab job runner that's designed to solve this particular pain point of runnung `cron` in containers, so I figured you might want to give it a shot! It's over here: https://github.com/aptible/supercronic

To use it with django-crontab, all you need to do is generate the `crontab` with `django-crontab`, then point `supercronic` at the `crontab` that was generated by `django-crontab` (instead of running `cron -f`).

(@kraiz - do feel free to remove the Supercronic tip if you think this kind of promotion isn't appropriate!)

**Comment by kraiz** [comment]
Thx @krallin for your suggestions. I appreciate your hint on supertronic. Nowadays it's all about gluing things together and supertronic should work. I'm not sure if @mjdavies is still on board.
